DROP DATABASE IF EXISTS cms;

CREATE DATABASE cms DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_lithuanian_ci;

DROP USER IF EXISTS 'cms_admin'@'127.0.0.1';
    
CREATE USER 'cms_admin'@'127.0.0.1' IDENTIFIED BY 'mysql';

GRANT ALL PRIVILEGES ON cms.* TO 'cms_admin'@'127.0.0.1' WITH GRANT OPTION;
